apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo
  labels:
    application: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: demo
    spec:
      containers:
        - name: demo
          image: "registry.pcld.busanbank.co.kr:5000/demo:latest"
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
      application: demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: demo