apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  name: demo
spec:
  tls:
  - secretName: demo-ingress-secret
  rules:
  - host: demo.default.101.55.50.245.nip.io
    http:
     paths:
     - backend:
         serviceName: demo
         servicePort: 80